version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_HOST=3.139.107.26
      - DB_PORT=3306
      - DB_NAME=database-screenspace
      - DB_USER=admin
      - DB_PASSWORD=screenspace
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=screenspace
      - MYSQL_DATABASE=database-screenspace
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=screenspace
