version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_HOST=database-screenspace-instance-1.cfo9syysrsej.us-east-2.rds.amazonaws.com
      - DB_PORT=3306
      - DB_NAME=screenspace
      - DB_USER=admin
      - DB_PASSWORD=screenspace
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=screenspace
      - MYSQL_DATABASE=screenspace
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=screenspace
